version: "3.9"
services:
  webvosk:
    build:
      context: .
      dockerfile: ./VoskApi/Dockerfile
    ports:
      - "80"
    networks:
      - vosknet
    environment:
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webvosk
    ports:
      - "4000:4000"
    networks:
      - vosknet
      
networks:
  vosknet: